// Generated by apps/server/scripts/docs-render.mjs from docs/user-guide/en/admin-guide.md — do not edit directly.
export const title = "Administrator Guide";
export const html = `<h1>Administrator Guide</h1>
<p><strong>Audience:</strong> lab administrators and lab managers.<br><strong>Purpose:</strong> every administrative capability the site actually has, where to find it, and how to use it safely.<br><strong>Prerequisites:</strong> an ADMIN or LAB_MANAGER account (most of the admin dashboard; account/invitation management is ADMIN-only — see Roles below).</p>
<h2>Roles, in short</h2>
<p>The app has exactly three roles: <strong>MEMBER</strong>, <strong>LAB_MANAGER</strong>, <strong>ADMIN</strong> (each strictly including the one before it, except for accounts). There is no separate &quot;site owner&quot; role inside the app — that is you, operating outside it, via the Vercel and Turso dashboards (see the Site Owner/Maintainer Guide).</p>
<table>
<thead>
<tr>
<th>Capability</th>
<th align="center">MEMBER</th>
<th align="center">LAB_MANAGER</th>
<th align="center">ADMIN</th>
</tr>
</thead>
<tbody><tr>
<td>Own profile, own content</td>
<td align="center">✓</td>
<td align="center">✓</td>
<td align="center">✓</td>
</tr>
<tr>
<td>Admin dashboard, content management, visibility, moderation</td>
<td align="center"></td>
<td align="center">✓</td>
<td align="center">✓</td>
</tr>
<tr>
<td>Accounts: invite, create, delete, change role</td>
<td align="center"></td>
<td align="center"></td>
<td align="center">✓</td>
</tr>
</tbody></table>
<h2>Admin login and dashboard</h2>
<p>Sign in at <code>/login</code> with an ADMIN or LAB_MANAGER account, then open <strong>Account → Admin Dashboard</strong> in the header (also directly at <code>/admin</code>). The dashboard overview summarizes account and content counts at a glance.</p>
<h2>Researcher onboarding (invitations) — ADMIN only</h2>
<p><strong>Where:</strong> Admin Dashboard → <strong>People</strong> (<code>/admin/people</code>).<br><strong>What it does:</strong> invites a new researcher without ever setting, seeing, or receiving their password.<br><strong>Required permission:</strong> ADMIN. LAB_MANAGER does not see this section at all, and the underlying API refuses it server-side even if attempted directly.</p>
<p><strong>Step by step:</strong></p>
<ol>
<li>Open People, click <strong>Invite a researcher</strong>.</li>
<li>Enter the researcher&#39;s email and choose their account role (Member / Lab manager / Admin).</li>
<li>Choose how their team profile is handled: link to an existing unlinked profile, create a brand-new one (name, initials, role/title, category), or no profile (an account-only login).</li>
<li>Click <strong>Generate invitation link</strong>. A dialog shows the one-time link — click <strong>Copy link</strong>.</li>
<li>Send that link to the researcher <strong>privately</strong> (email, chat, in person) — never post it anywhere public.</li>
<li>Close the dialog. <strong>The link cannot be retrieved again</strong> — this server never stores the raw link, only a one-way hash of it. If it&#39;s lost before the researcher receives it, revoke it and generate a new one.</li>
</ol>
<p><strong>What to check afterward:</strong> the <strong>Pending &amp; past invitations</strong> list on the same page shows every invitation&#39;s status — Pending, Accepted, Expired or Revoked — who sent it, and when it expires. Once the researcher accepts, their account appears in the Accounts list above.</p>
<p><strong>Revoking:</strong> click <strong>Revoke</strong> on any still-pending invitation to invalidate it immediately — use this if you sent it to the wrong address or it&#39;s no longer needed. A revoked or expired link cannot be un-revoked; generate a new invitation instead.</p>
<p><strong>Common mistakes:</strong></p>
<ul>
<li>Pasting the link somewhere semi-public (a shared channel, a ticket visible to others) — treat it exactly like a password.</li>
<li>Inviting the same email twice while a first invitation is still pending — the system refuses this (revoke the first one, or wait for it to be used/expire).</li>
<li>Expecting to see the researcher&#39;s password anywhere — by design, you never will, at any point.</li>
</ul>
<p><strong>Security considerations:</strong> every invitation token is a 256-bit random value; only its SHA-256 hash is ever stored; it is single-use and expires after 7 days; creating, revoking and accepting one are all recorded in the audit log without ever including the token itself.</p>
<h2>Managing existing accounts</h2>
<p>Still on <strong>People</strong> (<code>/admin/people</code>): the <strong>Accounts</strong> list shows every login, its role, and whether it&#39;s linked to a team profile.</p>
<ul>
<li><strong>Change role</strong>: use the role dropdown on any account (not your own — you can&#39;t change your own role, which guarantees at least one admin always remains).</li>
<li><strong>Link / unlink a team profile</strong>: connect an existing login to an existing unlinked profile, or disconnect one (the profile itself is kept, just unlinked).</li>
<li><strong>Delete an account</strong>: removes the login only; its linked team profile (if any) is kept and becomes unlinked, not deleted.</li>
</ul>
<h2>Content management</h2>
<p>The admin dashboard&#39;s other sections are a management view over what managers can already do through the ordinary site — they add no extra power beyond what&#39;s listed in Roles above:</p>
<ul>
<li><strong>Content</strong> (<code>/admin/content</code>): a browsable overview across content types, with visibility controls (public/lab-only, including bulk changes).</li>
<li><strong>Events</strong> (<code>/admin/events</code>): manage lab events.</li>
<li><strong>Community</strong> (<code>/admin/community</code>): forum category management and moderation.</li>
<li><strong>Files</strong> (<code>/admin/files</code>): manage uploaded files and gallery items.</li>
<li><strong>Translations</strong> (<code>/admin/translations</code>): manage Japanese overrides for translatable content.</li>
<li><strong>Audit</strong> (<code>/admin/audit</code>): the activity log — who did what, when. Account-level events (account created/deleted, role changed, invitation created/accepted/revoked) are visible to ADMIN only; other audited actions are visible to any manager.</li>
</ul>
<h2>Account lifecycle, end to end</h2>
<ol>
<li><strong>Invite</strong> (ADMIN) → 2. <strong>Researcher accepts, chooses their own password</strong> → 3. account is active, same as any other → 4. role changes and profile linking (ADMIN) as needed → 5. <strong>delete</strong> (ADMIN) when someone leaves — their team profile and any content they created are kept, simply no longer tied to a login.</li>
</ol>
<h2>Safe handling of invitations — summary</h2>
<ul>
<li>The invitation link is a credential. Treat it like a password: send it privately, never store it anywhere else, and revoke it if you&#39;re unsure it reached only the right person.</li>
<li>You will never be shown, nor need to know, a researcher&#39;s password at any point — not at invitation, not afterward.</li>
<li>If a researcher is locked out and has forgotten their password, there is currently no self-service reset — delete the old account (or leave it) and send a fresh invitation instead (see Known Limitations in the Site Owner/Maintainer Guide).</li>
</ul>
<p><strong>Related documentation:</strong> Researcher Onboarding Guide · Site Owner/Maintainer Guide</p>
`;
