// Generated by apps/server/scripts/docs-render.mjs — do not edit directly.
export interface DocManifestEntry { slug: string; titleEn: string; titleJa: string; }
export const DOCS_MANIFEST: DocManifestEntry[] = [
  {
    "slug": "admin-guide",
    "titleEn": "Administrator Guide",
    "titleJa": "管理者ガイド"
  },
  {
    "slug": "public-visitor-guide",
    "titleEn": "Public Visitor Guide",
    "titleJa": "一般訪問者ガイド"
  },
  {
    "slug": "quick-start",
    "titleEn": "Quick Start Guide",
    "titleJa": "クイックスタートガイド"
  },
  {
    "slug": "researcher-guide",
    "titleEn": "Researcher / Lab Member Guide",
    "titleJa": "研究者/ラボメンバー向けガイド"
  },
  {
    "slug": "researcher-onboarding",
    "titleEn": "Researcher Onboarding Guide",
    "titleJa": "研究者オンボーディングガイド"
  },
  {
    "slug": "site-maintainer-guide",
    "titleEn": "Site Owner / Maintainer Guide",
    "titleJa": "サイトオーナー/運用者向けガイド"
  }
];
