// Generated by apps/server/scripts/docs-render.mjs from docs/user-guide/en/public-visitor-guide.md — do not edit directly.
export const title = "Public Visitor Guide";
export const html = `<h1>Public Visitor Guide</h1>
<p><strong>Audience:</strong> anyone visiting the Smart Computing Lab website without an account.<br><strong>Purpose:</strong> find your way around the public site — research, people, publications, news, events and more — with no login required.<br><strong>Prerequisites:</strong> none. A web browser and the site&#39;s URL are all you need.</p>
<h2>What&#39;s on the site</h2>
<p>The header groups everything into three menus, plus two standalone links:</p>
<ul>
<li><strong>Research</strong> — Research Areas, Projects, Publications, Knowledge, Resources</li>
<li><strong>People</strong> — Team, Groups</li>
<li><strong>Community</strong> — Forum, News, Events, Gallery</li>
<li><strong>Contact</strong> — a standalone link</li>
<li><strong>Log in</strong> — top right, for lab members</li>
</ul>
<p>Some content is marked <strong>lab-only</strong> by its owners and is not shown to a public visitor; everything described below is what guests can actually see. A <strong>language switcher</strong> in the header toggles the whole site between English and Japanese at any time — it does not reload the page or lose your place.</p>
<h2>Home</h2>
<p>The landing page (<code>/</code>) gives a quick overview: a short lab introduction, highlighted research areas, a handful of recent news items, and quick links into the rest of the site. It&#39;s the fastest way to get oriented before diving into a specific section.</p>
<h2>Research Areas</h2>
<p><code>/research</code> lists the lab&#39;s broad research themes (for example, computer vision or FPGA/VLSI design), each with a short description. Click one (<code>/research/:id</code>) to see its detail page: a longer description plus the projects, researchers, publications, news and events connected to that area — each filtered to what is publicly visible.</p>
<h2>Projects</h2>
<p><code>/projects</code> lists concrete research projects, each showing its status (planned, active, completed, or archived) and the research group running it. A project&#39;s own page (<code>/projects/:id</code>) lists its members, the research areas and publications it is linked to, and any public events tied to it.</p>
<h2>Team</h2>
<p><code>/team</code> is the researcher roster: faculty, PhD/MSc/BSc researchers and other categories, each with a photo (or initials), role and department. Click a name (<code>/team/:id</code>) for that researcher&#39;s public profile — bio, history, and the publications, news, projects, groups and events they&#39;re connected to, all filtered to what is public.</p>
<h2>Groups</h2>
<p><code>/groups</code> lists the lab&#39;s research groups; each group&#39;s page (<code>/groups/:id</code>) shows its description and its public projects and members.</p>
<h2>Publications</h2>
<p><code>/publications</code> is a filterable, sortable list of the lab&#39;s papers (by year, with search). Each publication&#39;s page (<code>/publications/:id</code>) shows its full author list (linking to team profiles where available), venue, year, and any available links (PDF, DOI).</p>
<h2>News</h2>
<p><code>/news</code> lists lab announcements and updates — awards, accepted papers, open positions and similar — newest first, each optionally linked to the project it&#39;s about.</p>
<h2>Events</h2>
<p><code>/events</code> lists upcoming and past lab events (seminars, meetings, deadlines, social events), each showing its date, time, location and kind. An event&#39;s own page (<code>/events/:id</code>) shows its full description and any related project.</p>
<h2>Gallery</h2>
<p><code>/gallery</code>, where visible, shows photos from lab life, events and research, organized by category.</p>
<h2>Knowledge</h2>
<p><code>/knowledge</code> lists the lab&#39;s public documentation — methods notes, dataset documentation, procedures — that the lab has chosen to publish. A document&#39;s page (<code>/knowledge/:id</code>) shows its full body text.</p>
<h2>Resources</h2>
<p><code>/resources</code> lists the lab&#39;s public research infrastructure — datasets, hardware, software, tools and similar — with details on each (<code>/resources/:id</code>): version, vendor, identifier, environment notes and links to related projects, publications, events or knowledge documents.</p>
<h2>Community Forum</h2>
<p><code>/community/forum</code> shows forum categories that have been made public. A public category&#39;s topics and comments are readable without an account; posting, commenting and reacting all require a login (see the Researcher Guide).</p>
<h2>Search</h2>
<p><code>/search</code> searches across the site&#39;s public content — projects, publications, team members, news, research areas and more — in one place.</p>
<h2>Contact</h2>
<p><code>/contact</code> gives ways to reach the lab.</p>
<h2>Signing in</h2>
<p>The <strong>Log in</strong> link in the header is for existing lab accounts only — see the Researcher Guide. This site does not offer public self-registration; a lab administrator creates every account (see the Administrator Guide).</p>
<h2>Common questions</h2>
<ul>
<li><strong>I don&#39;t see a page I expected.</strong> It may be marked lab-only by its owner, or it may not be published yet — this is intentional, not a bug.</li>
<li><strong>The page is in the wrong language.</strong> Use the language switcher in the header; your choice is remembered on this device.</li>
<li><strong>Can I create my own account?</strong> Not directly — contact the lab (see Contact) and ask an administrator to invite you.</li>
</ul>
<p><strong>Related documentation:</strong> Quick Start Guide · Researcher/Lab Member Guide</p>
`;
