// Generated by apps/server/scripts/docs-render.mjs from docs/user-guide/en/quick-start.md — do not edit directly.
export const title = "Quick Start Guide";
export const html = `<h1>Quick Start Guide</h1>
<p><strong>Audience:</strong> anyone new to the site — visitor or newly-invited member.<br><strong>Purpose:</strong> get oriented in about five minutes.<br><strong>Prerequisites:</strong> none.</p>
<h2>1. Access the website</h2>
<p>Open the site&#39;s URL in any browser. No account is needed to browse.</p>
<h2>2. Activate your account (invited members only)</h2>
<p>If a lab administrator has invited you, you received a private link (<code>/invite/&lt;token&gt;</code>). Open it, confirm it shows your email, and choose your own password — no one else, including the administrator, will ever see it. This activates your account and logs you in immediately. (No invitation yet? See Contact below.)</p>
<h2>3. Log in</h2>
<p>Click <strong>Log in</strong> in the header, enter your email and password. <strong>Log out</strong> is in the Account menu once signed in.</p>
<h2>4. Complete your profile</h2>
<p>Once signed in, open <strong>Account → My Profile</strong> (<code>/profile</code>). Fill in your name, role/title, department, a short bio, and optionally a photo URL. This is what your public team page shows.</p>
<h2>5. Find research</h2>
<p>Use the <strong>Research</strong> menu for Research Areas, Projects, Publications, Knowledge documents and lab Resources.</p>
<h2>6. Find researchers</h2>
<p>Use the <strong>People</strong> menu for the Team roster and Research Groups. Click any name for their full public profile.</p>
<h2>7. Find publications &amp; projects</h2>
<p><code>/publications</code> and <code>/projects</code> each support filtering and search; a Research Area&#39;s own page also rolls up everything connected to it.</p>
<h2>8. Use member features (once logged in)</h2>
<ul>
<li><strong>Workspace</strong> — your own projects, groups and research areas in one place.</li>
<li><strong>Messages</strong> / <strong>Notifications</strong> — private conversations and activity addressed to you.</li>
<li><strong>Community → Forum</strong> — post, comment and react in categories you can see.</li>
<li>Add publications, news, research areas, events, knowledge docs, resources and gallery items — all start as lab-only until a manager publishes them.</li>
</ul>
<h2>9. Get help</h2>
<p>See the fuller <strong>Public Visitor Guide</strong> or <strong>Researcher/Lab Member Guide</strong>, or use <strong>Contact</strong> in the header to reach the lab directly.</p>
<h2>10. Log out</h2>
<p>Account menu → <strong>Log out</strong>, from any page.</p>
<p><strong>Related documentation:</strong> Public Visitor Guide · Researcher/Lab Member Guide · Researcher Onboarding Guide</p>
`;
