// Generated by apps/server/scripts/docs-render.mjs from docs/user-guide/en/researcher-onboarding.md — do not edit directly.
export const title = "Researcher Onboarding Guide";
export const html = `<h1>Researcher Onboarding Guide</h1>
<p><strong>Audience:</strong> a researcher who has just received an invitation to join the lab&#39;s website.<br><strong>Purpose:</strong> walk through activation, start to finish.<br><strong>Prerequisites:</strong> an invitation link from a lab administrator.</p>
<blockquote>
<p><strong>Do not share your password with the lab administrator or any other person.</strong> You are the only person who will ever know it — the administrator who invited you cannot see it, set it, or recover it.</p>
</blockquote>
<h2>1. Receiving the invitation</h2>
<p>Your administrator will send you a link privately (email, chat, or in person) — something like <code>https://&lt;site&gt;/invite/&lt;a long random code&gt;</code>. Treat this link like a password: it alone is enough to create your account. It works <strong>once</strong>, and expires <strong>7 days</strong> after it was generated.</p>
<h2>2. Opening the invitation link</h2>
<p>Open the link in a browser. If it&#39;s valid, you&#39;ll see a short activation form greeting you by your email address. If instead you see &quot;invalid, expired, or already used,&quot; the link can&#39;t be reused — ask your administrator for a new one (this also happens if you accidentally open an old link a second time after already activating).</p>
<h2>3. Setting a personal password</h2>
<p>Choose a password (at least 8 characters) and confirm it. This is the ONLY place you ever set it — nowhere in this process does the administrator choose it for you, see it, or ask you to tell them what it is. Submit the form.</p>
<h2>4. Activation</h2>
<p>Submitting creates your account and signs you in immediately — no separate login step needed right after activating.</p>
<h2>5. Completing your profile</h2>
<p>Go to <strong>Account → My Profile</strong> and fill in your name, role/title, department and a short bio (a photo URL is optional). This is what your public team page shows to visitors.</p>
<h2>6. Adding research information</h2>
<p>Once your profile exists, you can:</p>
<ul>
<li>Add publications, news items, and research areas</li>
<li>Create or join projects and research groups (ask a project/group lead or manager to add you as a member, or create your own)</li>
<li>Add lab resources and knowledge documentation related to your work</li>
</ul>
<p>Everything you create starts as <strong>lab-only</strong> (visible to signed-in members, not the public) until a manager publishes it — nothing you post becomes public by accident.</p>
<h2>7. Checking your account settings</h2>
<p>On <strong>My Profile</strong>, the <strong>Password</strong> section lets you change your password any time — you&#39;ll need your current one. There is no other account setting to configure; your role and any profile category are managed by an administrator.</p>
<h2>8. Logging in normally, afterward</h2>
<p>From now on, just use <strong>Log in</strong> in the header with your email and the password you chose. The invitation link itself is now permanently used up and will not work again — bookmark <code>/login</code> instead, not the invitation link.</p>
<h2>9. What you can edit vs. what needs an administrator</h2>
<p>See the full table in the Researcher/Lab Member Guide. In short: your own profile, your own password, and your own content, always. Your account role, deletion, and another member&#39;s content need a manager or admin.</p>
<h2>10. Password &amp; security best practices</h2>
<ul>
<li>Choose a password you don&#39;t reuse elsewhere.</li>
<li>Never share it with anyone, including your lab administrator — they will never legitimately ask you for it.</li>
<li>If you think your account may be compromised, tell your administrator — they can deactivate the account; you&#39;ll need a fresh invitation to reactivate.</li>
<li>There is currently no self-service &quot;forgot password&quot; option if you&#39;re logged out — contact your administrator.</li>
</ul>
<p><strong>Related documentation:</strong> Quick Start Guide · Researcher/Lab Member Guide</p>
`;
