// Generated by apps/server/scripts/docs-render.mjs from docs/user-guide/en/researcher-guide.md — do not edit directly.
export const title = "Researcher / Lab Member Guide";
export const html = `<h1>Researcher / Lab Member Guide</h1>
<p><strong>Audience:</strong> researchers, students, faculty and other authenticated lab members.<br><strong>Purpose:</strong> everything a signed-in member can do — your account, your profile, and the collaboration features available once you&#39;re logged in.<br><strong>Prerequisites:</strong> an active lab account. If you don&#39;t have one yet, see &quot;Account activation&quot; below, or the separate Researcher Onboarding Guide.</p>
<h2>Account activation</h2>
<p>Lab accounts are created only by an administrator — there is no public sign-up form. When an admin invites you, you receive a private link (<code>/invite/&lt;token&gt;</code>), valid for <strong>7 days</strong> and usable <strong>only once</strong>. Opening it shows your email address and a form to choose your own password; the administrator who invited you never sees, sets, or receives that password — you are the only person who ever knows it. Submitting the form activates your account and logs you in immediately. See the Researcher Onboarding Guide for the full walkthrough.</p>
<p>If your invitation link has expired or was already used, ask your administrator for a new one — your old link cannot be reused or extended.</p>
<h2>Logging in and out</h2>
<p>Use <strong>Log in</strong> in the header (<code>/login</code>) with your email and password. <strong>Log out</strong> is in the Account menu once you&#39;re signed in. Sessions last about a week of inactivity; logging in again is always safe.</p>
<h2>Changing your password</h2>
<p>On your <strong>Profile</strong> page (<code>/profile</code>), the <strong>Password</strong> section lets you change your own password at any time: enter your current password and your new one. This never involves the administrator — only you can change your own password this way, and only by first proving you know the current one. There is currently no self-service &quot;forgot password&quot; flow if you&#39;re logged out and don&#39;t remember your password — ask your administrator, who can deactivate the old account and send a fresh invitation.</p>
<h2>Your profile</h2>
<p><code>/profile</code> shows your own team profile (if one is linked to your account — ask your admin if you don&#39;t have one yet) with an edit form for:</p>
<ul>
<li>Full name, initials, role/title, department, short bio, photo URL</li>
</ul>
<p><strong>Category</strong> (e.g. Faculty/PhD/MSc/BSc/Research) and your position in listings are set by a manager or admin, not by you — this keeps the roster&#39;s organization consistent. Your public profile (<code>/team/:id</code>) is visible to everyone, including guests, except for anything your profile links to that is itself marked lab-only.</p>
<h2>What you can edit vs. what needs an administrator</h2>
<table>
<thead>
<tr>
<th>You can do yourself</th>
<th>Needs a manager or admin</th>
</tr>
</thead>
<tbody><tr>
<td>Edit your own profile fields</td>
<td>Change your account role</td>
</tr>
<tr>
<td>Change your own password</td>
<td>Create or delete accounts</td>
</tr>
<tr>
<td>Create publications, news, research areas</td>
<td>Delete most content, or change its visibility (public/lab-only)</td>
</tr>
<tr>
<td>Create events, knowledge documents, lab resources, gallery items you own, and edit/delete your own</td>
<td>Edit or delete another member&#39;s owned content</td>
</tr>
<tr>
<td>Post, comment and react in the forum</td>
<td>Moderate the forum (pin/lock/hide/move/delete others&#39; posts)</td>
</tr>
<tr>
<td>Message other members; manage your own notifications</td>
<td>—</td>
</tr>
</tbody></table>
<p>A <strong>lab manager</strong> has all of the above plus broader content management (visibility, deletion, project/group settings, moderation, the admin dashboard) — but never account/role management, which stays admin-only.</p>
<h2>Research &amp; collaboration</h2>
<ul>
<li><strong>Projects &amp; Groups</strong> (<code>/projects</code>, <code>/groups</code>): any member can create a new project or group; a project or group <strong>lead</strong> can manage its own membership.</li>
<li><strong>Workspace</strong> (<code>/workspace</code>, signed-in only): a personal view of the projects, groups and research areas you&#39;re connected to.</li>
<li><strong>Publications, News, Research Areas</strong>: any signed-in member can add one.</li>
<li><strong>Knowledge</strong> (<code>/knowledge</code>): add documentation; edit or delete your own, or anything once you&#39;re a manager.</li>
<li><strong>Resources</strong> (<code>/resources</code>): add lab resources/infrastructure records; same ownership rule as Knowledge.</li>
<li><strong>Events</strong> (<code>/events</code>): create events; edit/delete your own.</li>
<li><strong>Gallery</strong> (<code>/gallery</code>): add photos; edit/delete your own.</li>
</ul>
<p>New content you create defaults to <strong>lab-only</strong> visibility (visible to signed-in members, not to guests) unless a manager publishes it — this is deliberate: nothing you post is public by accident.</p>
<h2>Community</h2>
<ul>
<li><strong>Forum</strong> (<code>/community/forum</code>): post topics, comment, and react in any category you can see. Editing your own post or comment is always available while it&#39;s yours; a manager may hide, lock, pin, move or delete content as part of moderation.</li>
<li><strong>Messages</strong> (<code>/messages</code>, signed-in only): private one-to-one conversations with other members. No one else — not even an admin — can read your messages.</li>
<li><strong>Notifications</strong> (<code>/notifications</code>): mentions, replies, reactions and similar activity addressed to you.</li>
</ul>
<h2>Visibility &amp; privacy rules, in short</h2>
<ul>
<li>Content is <strong>PUBLIC</strong> (anyone, including guests) or <strong>LAB_ONLY</strong> (signed-in members only); only a manager/admin changes which.</li>
<li>Your private messages are visible only to you and the other participant.</li>
<li>Your profile shows only what you or a manager chose to fill in; anything it links to is still subject to that linked item&#39;s own visibility.</li>
</ul>
<h2>Common problems</h2>
<ul>
<li><strong>&quot;No team profile is linked to your account yet.&quot;</strong> Your login exists but isn&#39;t connected to a researcher profile — ask your administrator to link or create one.</li>
<li><strong>A page says Forbidden (403).</strong> You&#39;re logged in, but the action needs manager or admin permission.</li>
<li><strong>My invitation link doesn&#39;t work.</strong> It has either already been used or has expired (7 days) — ask your administrator for a new one.</li>
</ul>
<p><strong>Related documentation:</strong> Quick Start Guide · Researcher Onboarding Guide · Public Visitor Guide</p>
`;
