// Generated by apps/server/scripts/docs-render.mjs from docs/user-guide/ja/site-maintainer-guide.md — do not edit directly.
export const title = "サイトオーナー/運用者向けガイド";
export const html = `<h1>サイトオーナー/運用者向けガイド</h1>
<p><strong>対象者：</strong> Smart Computing Labウェブサイトの技術的な運用担当者<br><strong>目的：</strong> このコードベースを安全に運用・変更・デプロイするために必要な実務知識をまとめる<br><strong>前提条件：</strong> Node.js、npm、git。Prisma、Express、Reactの基礎知識があることを前提とします。</p>
<p>本ガイドは、実際に存在するリポジトリの内容を説明するものです。実装の経緯や設計根拠については <code>docs/architecture/*.md</code> を参照してください — 本ガイドは実務上のリファレンス、<code>docs/architecture/</code> は設計の記録という位置づけです。</p>
<h2>リポジトリ構成</h2>
<p>npm workspacesによるモノレポ構成です。</p>
<pre><code>apps/server/    Express + Prisma によるAPI（TypeScript、ESM）
apps/web/       React + TypeScript + Vite によるフロントエンド（クライアントレンダリングのSPA）
packages/shared/  Zodスキーマ、権限ロジック、i18n辞書 — 両アプリから利用
api/            Vercelサーバーレス関数のエントリーポイント（apps/serverのExpressアプリをラップ）
docs/           本ガイド、その他のユーザーガイド、docs/architecture/（実装の経緯）
</code></pre>
<p><code>apps/server</code> には独自の <code>node_modules</code> はありません — npm workspacesによってすべての依存関係がリポジトリのルートにまとめられています。</p>
<h2>フロントエンド</h2>
<p>Vite + React + TypeScript、クライアントサイドレンダリングのみ（SSRなし）。ルーティングは <code>react-router-dom</code> の <code>BrowserRouter</code>（ルート定義は <code>apps/web/src/App.tsx</code>、ヘッダーのメニュー構成はデータ駆動の <code>components/navConfig.ts</code>）。大きい、またはあまり使われないルートは <code>React.lazy</code> で分割していますが、一部のページは意図的に分割せず即時読み込みにしています（<code>App.tsx</code> 冒頭のコメントを参照 — 分割したことで実際に再現されたブラウザテストのタイミングアサーション失敗があったため）。</p>
<h2>バックエンド</h2>
<p>Express 4、<code>/api</code> 配下にマウント（<code>apps/server/src/app.ts</code>）、<code>/robots.txt</code> と <code>/sitemap.xml</code> はドキュメントルートに配置。ルートは <code>apps/server/src/routes/*.routes.ts</code> にリソースごとに分かれており、<code>routes/index.ts</code> でまとめてマウントされています。認可は<strong>サーバー側でのみ</strong>強制されます（<code>middleware/auth.ts</code> の <code>requireAuth</code>／<code>requireCan</code>／<code>requireOwnerOrManager</code>、その裏側にある <code>packages/shared/src/permissions.ts</code> の純粋な権限判定関数群）。フロントエンド側で同じ関数を使っている箇所は見た目の制御（ボタンの表示・非表示）のみで、セキュリティ境界ではありません。</p>
<h2>共有パッケージ</h2>
<p><code>packages/shared</code> — Zodバリデーションスキーマ、権限ポリシー関数、英語／日本語のUI辞書（<code>i18n/en.ts</code> / <code>i18n/ja.ts</code>、フラットなキー→文字列のマップ。<code>TranslationKey</code> は英語のキーから導出されるため、日本語側が同じキー集合を定義していることをTypeScriptが型レベルで強制します）。このパッケージは<strong>ソースを直接参照せず、ビルドされたものを使う</strong>設計です：<code>main</code>／<code>exports</code> は <code>dist/</code> を指しており、これは自身の <code>build</code> スクリプト（<code>tsc</code>）で生成されます。このビルドは <code>postinstall</code> でも自動実行されるため、<code>npm install</code> を行うだけで常に最新の <code>dist/</code> が用意され、追加の手動ステップは不要です。</p>
<h2>データベース</h2>
<p><strong>Prisma 5.22.0</strong>、両環境ともSQLite系のデータソース（<code>provider = &quot;sqlite&quot;</code>）を使用します。</p>
<ul>
<li><strong>ローカル開発環境：</strong> <code>apps/server/prisma/dev.db</code> という通常のローカルSQLiteファイル。<code>DATABASE_URL=&quot;file:./dev.db&quot;</code> で指定。</li>
<li><strong>本番環境（Vercel）：</strong> Turso（ホスティングされたlibSQL）。<code>TURSO_DATABASE_URL</code> + <code>TURSO_AUTH_TOKEN</code> を使用し、<code>@prisma/adapter-libsql</code> + <code>@libsql/client</code>（Prismaの <code>driverAdapters</code> プレビュー機能）経由で接続します。<code>PrismaClient</code> を生成する箇所は <code>apps/server/src/lib/prisma.ts</code> の1箇所のみで、<code>TURSO_DATABASE_URL</code> が設定されているかどうかで自動的に接続方式を切り替えます。他のファイルがこの分岐を行うことはありません。</li>
</ul>
<p>libSQLアダプターを使っていても、Prisma 5.x のネイティブ「library」クエリエンジンはプロセス内で引き続き動作し、すべてのクエリをコンパイルします（アダプターが置き換えるのは低レベルのDB I/Oのみです）。詳細は <code>api/index.ts</code> 内の詳しいコメントと、下記の <code>binaryTargets</code> に関する注記を参照してください。</p>
<h2>環境変数</h2>
<table>
<thead>
<tr>
<th>変数</th>
<th>使用環境</th>
<th>用途</th>
</tr>
</thead>
<tbody><tr>
<td><code>DATABASE_URL</code></td>
<td>ローカル／テスト</td>
<td><code>file:./dev.db</code> または使い捨てのコピー</td>
</tr>
<tr>
<td><code>TURSO_DATABASE_URL</code></td>
<td>本番</td>
<td><code>&lt;production value&gt;</code></td>
</tr>
<tr>
<td><code>TURSO_AUTH_TOKEN</code></td>
<td>本番</td>
<td><code>&lt;secret&gt;</code></td>
</tr>
<tr>
<td><code>SESSION_SECRET</code></td>
<td>全環境</td>
<td><code>&lt;secret&gt;</code> — 本番環境では実際の値がないとアプリは起動を拒否します</td>
</tr>
<tr>
<td><code>TRUST_PROXY</code></td>
<td>全環境</td>
<td><code>0</code>（リバースプロキシなし）／<code>1</code>（信頼できるホップが1つ）— 下記「Trust Proxy」を参照</td>
</tr>
<tr>
<td><code>NODE_ENV</code></td>
<td>全環境</td>
<td><code>development</code> / <code>production</code></td>
</tr>
<tr>
<td><code>PUBLIC_BASE_URL</code></td>
<td>任意</td>
<td><code>/sitemap.xml</code> を有効化し、招待リンクを絶対URLにします。ローカル開発では省略可</td>
</tr>
<tr>
<td><code>BLOB_READ_WRITE_TOKEN</code></td>
<td>本番</td>
<td><code>&lt;provisioned automatically when Vercel Blob storage is attached&gt;</code></td>
</tr>
</tbody></table>
<p>シークレットと記載された変数の実際の値は、絶対にコミットしないでください。完全な注釈付き一覧は <code>apps/server/.env.example</code> を参照してください。</p>
<h2>セッションの仕組み</h2>
<p><code>express-session</code> に、カスタムのPrismaベースのストア（<code>lib/prismaSessionStore.ts</code>、テーブル名 <code>Session</code>）を組み合わせています — これは2つ目のネイティブドライバーを避けるための選択です。Cookie名は <code>scl.sid</code>、<code>HttpOnly</code>、<code>SameSite=Lax</code>、本番環境では <code>Secure</code>（<code>TRUST_PROXY</code> の設定<strong>に加えて</strong>、リバースプロキシが実際に <code>X-Forwarded-Proto: https</code> を送信している必要があります — 下記「Trust Proxy」を参照）。セッションIDはログイン時とパスワード変更時に再生成されます（セッション固定攻撃対策）。</p>
<h2>認証・認可</h2>
<p>bcryptによるパスワードハッシュ化（コスト係数10）。存在しないメールアドレスに対しては固定のダミーハッシュと比較することで、「アカウントが存在しない」と「パスワードが間違っている」をタイミングから区別できないようにしています。インメモリ・プロセス単位のログインレート制限（<code>lib/loginRateLimit.ts</code>）が <code>/api/auth/login</code> と <code>/api/auth/password</code> を保護します。研究者オンボーディング（<code>routes/invitations.routes.ts</code>）では、1回限り有効・7日間で期限切れ・SHA-256でハッシュ化された招待トークンを発行します — 管理者が研究者のパスワードを見たり設定したりすることはありません。詳細は管理者ガイドを参照してください。</p>
<p><strong>既知の制限事項：</strong> ログイン／招待のレート制限はプロセス単位のインメモリ実装です。Vercel上では関数インスタンスごとに独立したレート制限になるため、コールドスタートや複数インスタンスにまたがるとガードの効果が弱まります。ただし、その場合でも実際のリクエストには正しいパスワード／トークンが依然として必要です。</p>
<h2>ストレージ</h2>
<p>デュアルバックエンド構成（<code>lib/storage.ts</code>）：開発環境ではローカルファイルシステム、本番環境ではVercel Blob（プライベートアクセス）を使用し、<code>BLOB_READ_WRITE_TOKEN</code> が設定されているかどうかで自動的に切り替わります。ファイルはサーバーが生成した不透明な <code>storageKey</code> で参照され、ユーザーが指定したファイル名やパスがそのまま使われることはありません。<code>npm run storage:reconcile -w apps/server</code> で、孤立したBlob／レコードを検出・報告できます。</p>
<h2>ビルド・テスト・シード・マイグレーション</h2>
<pre><code>npm run build                        # shared -&gt; server -&gt; web の順にビルド
npm run dev                          # server（tsx watch）と web（vite）を並行起動
npm run migrate -w apps/server       # prisma migrate dev（ローカル用）
npm run seed -w apps/server          # べき等：管理者アカウントとサンプルコンテンツを、未作成の場合のみ作成
npm run test:unit -w apps/server     # サーバー・DBを起動しない純粋な単体テスト
npm run test:invitations -w apps/server   # 使い捨てのDBコピーに対して実サーバーを起動してテスト
</code></pre>
<p><code>apps/server/package.json</code> の <code>test:*</code> スクリプトの多くは同じパターンに従います：<code>dev.db</code> を使い捨ての一時ファイルにコピーし、そのコピーに対して実サーバーを起動し、実際のHTTP経由で操作し、終了後にコピーを破棄します。<strong>同じターミナルで本番のTursoに対する作業も行っている場合は、これらをローカルで実行する前に、必ずご自身のシェルで <code>TURSO_DATABASE_URL</code>／<code>TURSO_AUTH_TOKEN</code> を明示的にクリアしてください。</strong> これらのスクリプトの一部は、起動するサーバーの環境変数に <code>...process.env</code> を展開する際、この2つの変数を先にクリアしていないため、Tursoの認証情報が環境に残っていると、「ローカル」のはずのテストサーバーが実際の本番データベースに読み取り接続されてしまいます（書き込みは失敗したトランザクション内でロールバックされますが、スクリプトの意図とは異なる動作になるため、明示的にクリアしておくのが安全です）。</p>
<h2>デプロイ（Vercel + Turso）</h2>
<p><code>vercel.json</code>：<code>buildCommand</code> は <code>packages/shared</code> → <code>apps/web</code> の順にビルドします。<code>functions[&quot;api/index.ts&quot;]</code> ブロックが、Prismaのネイティブクエリエンジンのバイナリを関数に同梱します（<code>includeFiles</code>）。rewritesにより <code>/api/*</code> は関数へ、それ以外はビルド済みのSPAへ転送されます。<code>api/index.ts</code> は <code>PRISMA_QUERY_ENGINE_LIBRARY</code> を明示的に設定しています（VercelのFunctionランタイムはビルドコンテナ（Debianベース）とは異なりAmazon Linuxであるため、<code>prisma/schema.prisma</code> の <code>generator client</code> ブロックには <code>binaryTargets = [&quot;native&quot;, &quot;rhel-openssl-3.0.x&quot;]</code> が指定されています。<code>native</code> はローカル／CI用、<code>rhel-openssl-3.0.x</code> はデプロイされた関数用です。詳しい経緯は両ファイルのコメントを参照してください）。</p>
<p><strong>マイグレーションが本番環境に自動適用されることはありません。</strong> PrismaのマイグレーションコマンドはTursoのHTTPベースの接続をサポートしていないため、本番環境のマイグレーションは監査済みの一回限りのスクリプトを使って、実データベースに対して手動かつ意図的に適用します — 通常のデプロイの一部として自動実行されることは決してありません。</p>
<h2>ロールバックに関する考慮事項</h2>
<p>Vercelは過去のデプロイを保持しており、以前のデプロイに戻すのがアプリケーションコードの最も迅速なロールバック方法です。<strong>本プロジェクトの慣例として、データベースのマイグレーションは追加のみ</strong>です（カラムやテーブルを削除したことはこれまで一度もありません）。そのため、新しい追加型マイグレーションが適用された状態のままアプリケーションコードだけを古いバージョンに戻しても安全です（古いコードは単に新しいテーブル・カラムを使わないだけです）。マイグレーション自体を取り消すための自動化ツールはなく、必要な場合は、順方向のマイグレーションと同じ慎重かつ監査付きのプロセスで、レビュー済みの逆方向マイグレーションを手動で作成して適用します。</p>
<h2>ログ</h2>
<p>サーバーエラーは中央のエラーハンドラー（<code>app.ts</code>）で <code>console.error</code> によって記録されます。それ以外に外部のログ集約サービスへの接続は現時点ではありません — 標準出力／標準エラー出力は、プロセスを実行しているホスト（本番環境ではVercelの関数ログ）に出力されます。</p>
<h2>セキュリティ設定</h2>
<p>Helmetベースのセキュリティヘッダー（<code>lib/security.ts</code>）、このシングルオリジンアプリに適したCSP、<code>TRUST_PROXY</code> による明示的なクライアントIP信頼設定（<code>lib/trustProxy.ts</code> — 無条件の <code>trust proxy: 1</code> ではなく、環境変数による明示的な設定とドキュメント化がされています）、そしてサポートされている唯一のトポロジー：静的SPAビルドとAPIの両方の前段に1つのリバースプロキシを配置し、<code>/robots.txt</code>、<code>/sitemap.xml</code>、<code>/api/*</code> をサーバーへ、それ以外をSPAビルドへ振り分ける構成です。</p>
<h2>レート制限</h2>
<p>ログインとパスワード変更は（IP、メールアドレス）単位、招待の情報取得・承諾はIP単位で、いずれもインメモリ・プロセス単位です — 複数インスタンスに関する既知の制限事項は「認証・認可」を参照してください。</p>
<h2>バックアップ・復旧</h2>
<p>Tursoはホスティングプラットフォーム側でポイントインタイムリカバリを提供しています（保持期間はご利用のプランによりますので、Tursoのダッシュボード／ドキュメントをご確認ください）。本リポジトリ自体には独自のバックアップ機構はありません。ローカル開発の <code>dev.db</code> は使い捨てでgit管理対象外のファイルであり、バックアップは想定していません — シードスクリプト（<code>npm run seed</code>）でいつでも基本的なコンテンツを再生成できます。</p>
<h2>依存関係の更新</h2>
<p>通常の <code>npm outdated</code> / <code>npm update</code> の流れで行います。ルートの <code>package.json</code> の <code>allowScripts</code> 項目（<code>@prisma/client</code>、<code>@prisma/engines</code>、<code>esbuild</code>、<code>prisma</code>）は、インストールスクリプトを持つパッケージを明示的に許可するリストです。追加する前によく確認してください。</p>
<h2>ブラウザテスト</h2>
<p><code>apps/server/scripts/browser-regression.cjs</code> は、生のCDP（Chrome DevTools Protocol）経由で実際のヘッドレスブラウザを操作します — PlaywrightやPuppeteerへの依存はなく、ブラウザの実行ファイルを直接起動します。<code>BROWSER_PATH</code> で実行ファイルを指定します（デフォルトはWindowsのEdgeのパスですが、このコンテナやほとんどのLinux CIでは、あらかじめインストールされたChromiumを指すように設定されています）。<code>ONLY_*</code> 環境変数で特定フェーズのセクションのみを実行できます。</p>
<h2>フェーズ27の連携機能（すべて任意）</h2>
<p>詳細：<code>docs/architecture/phase27-lab-website-integrations.md</code>。</p>
<ul>
<li><strong>デプロイ順序：</strong> フェーズ27のマイグレーション（<code>20261008090552_phase27_integrations</code>、追加のみ）は、新しいコードがトラフィックを処理する <strong>前</strong> にTursoへ適用する必要があります。適用しないと <code>/api/team</code> と <code>/api/profile</code> が「no such column」で失敗します。Previewデプロイは本番データベースを共有するため、このブランチのPreviewも影響を受けます。明示的な承認なしに本番へ <code>migrate</code>/<code>seed</code> を実行しないでください。</li>
<li><strong>環境変数（プレースホルダーは <code>apps/server/.env.example</code>）：</strong> <code>PORTAL_URL</code>（Google SitesのURL、httpsのみ）、<code>GOOGLE_CLIENT_ID</code>・<code>GOOGLE_CLIENT_SECRET</code>・<code>GOOGLE_OAUTH_REDIRECT_URI</code>（3つすべて、または未設定）、<code>ORCID_CLIENT_ID</code>・<code>ORCID_CLIENT_SECRET</code>（任意・推奨）、<code>PUBLICATION_SYNC_CONTACT_EMAIL</code>・<code>PUBLICATION_SYNC_DELAY_MS</code>・<code>PUBLICATION_SYNC_BUDGET_MS</code>、<code>MAX_PROFILE_PHOTO_BYTES</code>。</li>
<li><strong>Google OAuthの設定：</strong> Google Cloud Consoleで「ウェブアプリケーション」のOAuthクライアントを作成し、環境ごとに <code>/api/auth/google/callback</code> で終わるリダイレクトURI（本番はhttps）を登録します。Googleで管理者セッションを取得できるのは、確認済みのアカウント <code>susmartcomputinglab@gmail.com</code> のみで、メールアドレスだけで自動的にリンクされることはありません。</li>
<li><strong>アップロードの問題：</strong> 管理者として <code>/api/files/storage-status?probe=1</code> を開きます。<code>STORAGE_NOT_CONFIGURED</code> はプロジェクトにBlobストア／トークンが接続されていないこと、<code>STORAGE_UNAVAILABLE</code> はバックエンドが書き込みを拒否したこと（Blobストアとアクセスモードを確認）を意味します。Vercelではアップロードは4 MBまでです。</li>
<li><strong>埋め込み不可：</strong> Cookieが <code>SameSite=Lax</code> のため、このアプリはGoogle Sitesの埋め込みでは動作しません。サイトからリンクしてください。</li>
<li><strong>Facebook：</strong> 未連携です（このプロジェクトには公式ページがありません）。必要な作業はアーキテクチャ文書を参照してください。</li>
</ul>
<h2>既知の制限事項</h2>
<ul>
<li>ログアウト状態のユーザー向けの自己解決型「パスワードをお忘れですか」機能はありません（メール送信が必要になるため、意図的に導入していません — 管理者ガイドの回避策（新しい招待の発行）を参照）。</li>
<li>ログイン／招待のレート制限は、複数のVercel関数インスタンス間で共有されない、プロセス単位の実装です。</li>
<li>Tursoが提供するもの以外に、自動化されたバックアップ機構はありません。</li>
<li>デフォルトでは外部のログ集約サービスには接続されていません。</li>
</ul>
<h2>運用チェックリスト（本番環境への変更前）</h2>
<ol>
<li><code>npm run build</code>、<code>npm run test:unit -w apps/server</code>、および関連する <code>test:*</code> のリグレッションスクリプトを実行する。</li>
<li>マイグレーションを伴う場合：追加のみであることを確認し、まずローカルで適用・検証したうえで、本番環境へはドキュメント化された手動プロセスでのみ適用する — 自動適用は行わない。</li>
<li>シークレット・トークン・認証情報が漏れる可能性がないか、差分をレビューする。</li>
<li>まずPreview環境にデプロイし、<code>/api/health</code> と実際のログインをスモークテストしてから本番環境に昇格させる。</li>
</ol>
<p><strong>関連ドキュメント：</strong> 管理者ガイド・実装の経緯は <code>docs/architecture/*.md</code> を参照</p>
`;
