// Generated by apps/server/scripts/docs-render.mjs from docs/user-guide/en/site-maintainer-guide.md — do not edit directly.
export const title = "Site Owner / Maintainer Guide";
export const html = `<h1>Site Owner / Maintainer Guide</h1>
<p><strong>Audience:</strong> the technical maintainer of the Smart Computing Lab website.<br><strong>Purpose:</strong> the operational knowledge needed to run, change and deploy this codebase safely.<br><strong>Prerequisites:</strong> Node.js, npm, git; familiarity with Prisma, Express and React is assumed.</p>
<p>This guide documents the repository as it actually exists. For deep implementation history and rationale, see <code>docs/architecture/*.md</code> — this guide is the practical operating reference; those are the design record.</p>
<h2>Repository structure</h2>
<p>An npm-workspaces monorepo:</p>
<pre><code>apps/server/    Express + Prisma API (TypeScript, ESM)
apps/web/       React + TypeScript + Vite frontend (SPA, client-rendered)
packages/shared/  Zod schemas, permissions, i18n dictionary — imported by both apps
api/            Vercel serverless function entry point (wraps apps/server&#39;s Express app)
docs/           This guide, the other user guides, and docs/architecture/ (implementation history)
</code></pre>
<p><code>apps/server</code> has no <code>node_modules</code> of its own — npm workspaces hoist every dependency to the repo root.</p>
<h2>Frontend</h2>
<p>Vite + React + TypeScript, client-side rendered only (no SSR). Routing is <code>react-router-dom</code>&#39;s <code>BrowserRouter</code> (<code>apps/web/src/App.tsx</code> for the route table, <code>components/navConfig.ts</code> for the header&#39;s information architecture, data-driven). Large/rarely-needed routes are <code>React.lazy</code>-split; a handful of pages are deliberately kept eager (see the comment block at the top of <code>App.tsx</code>) because splitting them broke specific, reproduced browser-test timing assertions.</p>
<h2>Backend</h2>
<p>Express 4, mounted under <code>/api</code> (<code>apps/server/src/app.ts</code>), plus <code>/robots.txt</code> and <code>/sitemap.xml</code> at the document root. Routes live in <code>apps/server/src/routes/*.routes.ts</code>, one file per resource, mounted in <code>routes/index.ts</code>. Authorization is enforced <strong>server-side only</strong> (<code>middleware/auth.ts</code>&#39;s <code>requireAuth</code>/<code>requireCan</code>/<code>requireOwnerOrManager</code>, backed by the pure policy functions in <code>packages/shared/src/permissions.ts</code>) — the frontend&#39;s own use of those same functions is cosmetic (hides buttons), never a security boundary.</p>
<h2>Shared package</h2>
<p><code>packages/shared</code> — Zod validation schemas, the permission-policy functions, and the English/Japanese UI dictionary (<code>i18n/en.ts</code> / <code>i18n/ja.ts</code>, flat key→string maps; <code>TranslationKey</code> is derived from English&#39;s keys, so TypeScript itself enforces that Japanese defines exactly the same set). It is a <strong>built, not source-resolved</strong> package: <code>main</code>/<code>exports</code> point at <code>dist/</code>, produced by its own <code>build</code> script (<code>tsc</code>), which also runs automatically via its <code>postinstall</code> so a fresh <code>npm install</code> always has a fresh <code>dist/</code> without an extra manual step.</p>
<h2>Database</h2>
<p><strong>Prisma 5.22.0</strong>, SQLite-family datasource (<code>provider = &quot;sqlite&quot;</code>) in both environments:</p>
<ul>
<li><strong>Local development</strong>: a plain local SQLite file, <code>apps/server/prisma/dev.db</code>, via <code>DATABASE_URL=&quot;file:./dev.db&quot;</code>.</li>
<li><strong>Production (Vercel)</strong>: Turso (hosted libSQL), via <code>TURSO_DATABASE_URL</code> + <code>TURSO_AUTH_TOKEN</code>, through <code>@prisma/adapter-libsql</code> + <code>@libsql/client</code> (Prisma&#39;s <code>driverAdapters</code> preview feature). <code>apps/server/src/lib/prisma.ts</code> is the single place <code>PrismaClient</code> is constructed, and picks the topology automatically based on whether <code>TURSO_DATABASE_URL</code> is set — no other file branches on this.</li>
</ul>
<p>Even with the libSQL adapter, Prisma 5.x&#39;s native &quot;library&quot; query engine still runs in-process to compile every query (the adapter only swaps the low-level DB I/O) — see <code>api/index.ts</code>&#39;s extensive comments and the <code>binaryTargets</code> note below.</p>
<h2>Environment variables</h2>
<table>
<thead>
<tr>
<th>Variable</th>
<th>Where</th>
<th>Purpose</th>
</tr>
</thead>
<tbody><tr>
<td><code>DATABASE_URL</code></td>
<td>local/test</td>
<td><code>file:./dev.db</code> or a disposable copy</td>
</tr>
<tr>
<td><code>TURSO_DATABASE_URL</code></td>
<td>production</td>
<td><code>&lt;production value&gt;</code></td>
</tr>
<tr>
<td><code>TURSO_AUTH_TOKEN</code></td>
<td>production</td>
<td><code>&lt;secret&gt;</code></td>
</tr>
<tr>
<td><code>SESSION_SECRET</code></td>
<td>all</td>
<td><code>&lt;secret&gt;</code> — the app refuses to start in production without a real value</td>
</tr>
<tr>
<td><code>TRUST_PROXY</code></td>
<td>all</td>
<td><code>0</code> (no reverse proxy) / <code>1</code> (exactly one trusted hop) — see Trust Proxy below</td>
</tr>
<tr>
<td><code>NODE_ENV</code></td>
<td>all</td>
<td><code>development</code> / <code>production</code></td>
</tr>
<tr>
<td><code>PUBLIC_BASE_URL</code></td>
<td>optional</td>
<td>enables <code>/sitemap.xml</code> and gives invitation links an absolute URL; omitted in local dev</td>
</tr>
<tr>
<td><code>BLOB_READ_WRITE_TOKEN</code></td>
<td>production</td>
<td><code>&lt;provisioned automatically when Vercel Blob storage is attached&gt;</code></td>
</tr>
</tbody></table>
<p>Never commit real values for any secret-marked variable — see <code>apps/server/.env.example</code> for the full annotated list.</p>
<h2>Session system</h2>
<p><code>express-session</code> with a custom Prisma-backed store (<code>lib/prismaSessionStore.ts</code>, table <code>Session</code>) — chosen specifically to avoid a second native driver. Cookie name <code>scl.sid</code>; <code>HttpOnly</code>; <code>SameSite=Lax</code>; <code>Secure</code> in production (requires <code>TRUST_PROXY</code> <strong>and</strong> the reverse proxy actually sending <code>X-Forwarded-Proto: https</code> — see Trust Proxy). Session id is regenerated on login (fixation resistance) and on password change.</p>
<h2>Authentication &amp; authorization</h2>
<p>bcrypt password hashing (cost 10); a fixed dummy hash is compared against for an unknown email so timing can&#39;t distinguish &quot;no such account&quot; from &quot;wrong password&quot;; an in-memory, per-process login rate limiter (<code>lib/loginRateLimit.ts</code>) guards <code>/api/auth/login</code> and <code>/api/auth/password</code>. Researcher onboarding (<code>routes/invitations.routes.ts</code>) issues single-use, 7-day, SHA-256-hashed invitation tokens — the admin never sees or sets the researcher&#39;s password; see the Administrator Guide.</p>
<p><strong>Known limitation</strong>: the login/invitation rate limiter is in-memory per process. On Vercel, each function instance has its own, so the guard&#39;s effectiveness degrades across cold starts/multiple instances — a real request still requires the correct password/token regardless.</p>
<h2>Storage</h2>
<p>Dual backend (<code>lib/storage.ts</code>): local filesystem in development, Vercel Blob (private access) in production, selected automatically by whether <code>BLOB_READ_WRITE_TOKEN</code> is set. Files are addressed by an opaque, server-generated <code>storageKey</code> — never a user-supplied name or path. <code>npm run storage:reconcile -w apps/server</code> finds and reports orphaned blobs/rows.</p>
<h2>Build, test, seed, migrate</h2>
<pre><code>npm run build                        # shared -&gt; server -&gt; web, in that order
npm run dev                          # concurrent server (tsx watch) + web (vite)
npm run migrate -w apps/server       # prisma migrate dev (local)
npm run seed -w apps/server          # idempotent: creates the admin account + sample content if absent
npm run test:unit -w apps/server     # pure unit tests, no server/DB
npm run test:invitations -w apps/server   # spawns a real server against a disposable DB copy
</code></pre>
<p>Most <code>test:*</code> scripts in <code>apps/server/package.json</code> follow the same pattern: copy <code>dev.db</code> to a disposable temp file, spawn the real server against the copy, drive it over real HTTP, discard the copy. <strong>Explicitly clear <code>TURSO_DATABASE_URL</code>/<code>TURSO_AUTH_TOKEN</code> in your own shell</strong> before running any of these locally if you&#39;ve also been working against production Turso in the same terminal — several of these scripts spread <code>...process.env</code> into the spawned server&#39;s environment without clearing those two first, so an ambient Turso credential silently redirects the &quot;local&quot; test server to the real production database for reads (writes inside a failing transaction roll back, but it&#39;s still not what the script intends, and it&#39;s worth being deliberate about).</p>
<h2>Deployment (Vercel + Turso)</h2>
<p><code>vercel.json</code>: <code>buildCommand</code> builds <code>packages/shared</code> then <code>apps/web</code>; a <code>functions[&quot;api/index.ts&quot;]</code> block ships the Prisma native query engine binary alongside the function (<code>includeFiles</code>); rewrites send <code>/api/*</code> to the function and everything else to the built SPA. <code>api/index.ts</code> sets <code>PRISMA_QUERY_ENGINE_LIBRARY</code> explicitly (Vercel&#39;s Function runtime is Amazon Linux, not the Debian-based build container, so <code>prisma/schema.prisma</code>&#39;s <code>generator client</code> block lists <code>binaryTargets = [&quot;native&quot;, &quot;rhel-openssl-3.0.x&quot;]</code> — <code>native</code> for local/CI, <code>rhel-openssl-3.0.x</code> for the deployed function; see the extensive comments in both files for the full root-cause history).</p>
<p><strong>Migrations are never auto-applied to production.</strong> Prisma&#39;s own <code>migrate deploy</code> does not support Turso&#39;s HTTP-based connection; production migrations are applied via an audited one-off script against the real database, run manually and deliberately — never as part of a routine deploy.</p>
<h2>Rollback considerations</h2>
<p>Vercel keeps previous deployments; redeploying an older one is the fastest rollback for application code. <strong>Database migrations are additive-only by convention in this project</strong> — nothing here has ever dropped a column or table — so rolling back application code while a newer, additive migration remains applied is safe (older code simply doesn&#39;t use the new table/columns). Rolling back a migration itself has no automated tooling here; it would be a manually-written, reviewed reverse migration, applied with the same deliberate, audited process as a forward one.</p>
<h2>Logging</h2>
<p>Server errors are logged via <code>console.error</code> in the central error handler (<code>app.ts</code>); nothing beyond that is currently wired to an external log aggregator — stdout/stderr on whatever host runs the process (Vercel&#39;s own function logs in production).</p>
<h2>Security configuration</h2>
<p>Helmet-based security headers (<code>lib/security.ts</code>), a CSP appropriate to this single-origin app, <code>TRUST_PROXY</code>-driven client-IP trust (<code>lib/trustProxy.ts</code> — explicit, environment-driven, documented rather than a blind <code>trust proxy: 1</code>), and the documented one supported topology: a single reverse proxy in front of both the static SPA build and the API, routing <code>/robots.txt</code>, <code>/sitemap.xml</code> and <code>/api/*</code> to the server and everything else to the SPA build.</p>
<h2>Rate limiting</h2>
<p>In-memory, per-process, per-(IP, email) for login and password-change, per-IP for invitation info/accept — see Authentication above for the known multi-instance caveat.</p>
<h2>Backups / recovery</h2>
<p>Turso provides point-in-time recovery on its own hosted platform (consult Turso&#39;s own dashboard/docs for your plan&#39;s retention window) — this repository does not implement its own backup mechanism. Local development&#39;s <code>dev.db</code> is a disposable, gitignored file with no backup expectation; the seed script (<code>npm run seed</code>) can always regenerate baseline content.</p>
<h2>Dependency updates</h2>
<p>Standard <code>npm outdated</code> / <code>npm update</code> workflow; <code>apps/server</code>&#39;s <code>allowScripts</code> entries in the root <code>package.json</code> are an explicit allow-list for packages with install scripts (<code>@prisma/client</code>, <code>@prisma/engines</code>, <code>esbuild</code>, <code>prisma</code>) — review before adding to it.</p>
<h2>Browser testing</h2>
<p><code>apps/server/scripts/browser-regression.cjs</code> drives a real headless browser over raw CDP (Chrome DevTools Protocol) — no Playwright/Puppeteer dependency; it spawns the browser binary directly. <code>BROWSER_PATH</code> selects the executable (defaults to a Windows Edge path; this container/most Linux CI sets it to a pre-installed Chromium). Supports <code>ONLY_*</code> env flags to run just one phase&#39;s section.</p>
<h2>Phase 27 integrations (all optional)</h2>
<p>Full details: <code>docs/architecture/phase27-lab-website-integrations.md</code>.</p>
<ul>
<li><strong>Deploy order:</strong> the Phase 27 migration (<code>20261008090552_phase27_integrations</code>, additive) must be applied to Turso <strong>before</strong> the new code serves traffic, or <code>/api/team</code> and <code>/api/profile</code> fail with &quot;no such column&quot;. Preview deployments share the production database, so a Preview of the branch is affected too. Never run <code>migrate</code>/<code>seed</code> against production without explicit approval.</li>
<li><strong>Environment variables (placeholders in <code>apps/server/.env.example</code>):</strong> <code>PORTAL_URL</code> (Google Sites link, https only); <code>FACEBOOK_PAGE_URL</code> (official Facebook Page link, https only, optional); <code>GOOGLE_CLIENT_ID</code>, <code>GOOGLE_CLIENT_SECRET</code>, <code>GOOGLE_OAUTH_REDIRECT_URI</code> (all three or none); <code>ORCID_CLIENT_ID</code>, <code>ORCID_CLIENT_SECRET</code> (optional, recommended); <code>PUBLICATION_SYNC_CONTACT_EMAIL</code>, <code>PUBLICATION_SYNC_DELAY_MS</code>, <code>PUBLICATION_SYNC_BUDGET_MS</code>; <code>MAX_PROFILE_PHOTO_BYTES</code>.</li>
<li><strong>Google OAuth setup:</strong> create a Web-application OAuth client in Google Cloud Console and register one redirect URI per environment ending in <code>/api/auth/google/callback</code> (https in production). Only the verified account <code>susmartcomputinglab@gmail.com</code> can obtain an admin session through Google; nobody is auto-linked by email.</li>
<li><strong>Upload problems:</strong> as an admin open <code>/api/files/storage-status?probe=1</code>. <code>STORAGE_NOT_CONFIGURED</code> means no Blob store/token is attached to the project; <code>STORAGE_UNAVAILABLE</code> means the backend refused a write (check the Blob store and its access mode). Uploads are capped at 4 MB on Vercel.</li>
<li><strong>Not embedded:</strong> the application does not work inside a Google Sites embed (cookies are <code>SameSite=Lax</code>); the Site links to it instead.</li>
<li><strong>Facebook:</strong> the home page shows a "Follow us on Facebook" link when <code>FACEBOOK_PAGE_URL</code> is set to the lab's official Page (https, on facebook.com / www.facebook.com / m.facebook.com, e.g. <code>https://www.facebook.com/&lt;page-name&gt;</code>); otherwise it shows "Facebook updates are not connected yet" (the same happens if the value is not acceptable — the server then logs one warning at startup). A copied link's tracking parameters (<code>mibextid</code>, <code>ref</code>, <code>fbclid</code>) are removed automatically; any other query string is refused. Only the link is supported — recent posts are <strong>not</strong> retrieved or shown, and no Facebook token or app is used. Showing posts would need an official Page and an authorized Meta integration; see the architecture document.</li>
</ul>
<h2>Known limitations</h2>
<ul>
<li>No self-service &quot;forgot password&quot; flow for a logged-out user (would require email delivery, deliberately not introduced — see the Administrator Guide&#39;s workaround: a fresh invitation).</li>
<li>Login/invitation rate limiting is per-process, not shared across Vercel function instances.</li>
<li>No automated backup mechanism beyond what Turso itself provides.</li>
<li>No external log aggregation wired up by default.</li>
</ul>
<h2>Operational checklist (before a production change)</h2>
<ol>
<li>Run <code>npm run build</code>, <code>npm run test:unit -w apps/server</code>, and the relevant <code>test:*</code> regression scripts.</li>
<li>If a migration is involved: confirm it&#39;s additive, apply and verify it locally first, and apply it to production only via the documented manual process — never automatically.</li>
<li>Review the diff for anything that could expose a secret, token or credential.</li>
<li>Deploy a Preview first; smoke-test <code>/api/health</code> and a real login before promoting to Production.</li>
</ol>
<p><strong>Related documentation:</strong> Administrator Guide · <code>docs/architecture/*.md</code> for implementation history</p>
`;
