/**
 * Renders docs/user-guide/{en,ja}/*.md to HTML, once, at build/generate time — not in the
 * browser. The web app's /docs pages import the generated .ts modules directly (plain string
 * constants, no markdown parser shipped to the client); apps/server/scripts/docs-pdf.mjs reuses
 * the exact same generated HTML for the PDF versions, so there is exactly one rendering of each
 * guide, never two copies that could drift apart.
 *
 * Fails loudly (non-zero exit) if English and Japanese don't define the same set of guides —
 * mirrors the same "both languages must stay in sync" discipline packages/shared/src/i18n already
 * enforces for the UI dictionary (see scripts/unit-i18n.test.ts).
 *
 *   node scripts/docs-render.mjs
 *   npm run docs:render -w apps/server
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { marked } from "marked";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..", "..", "..");
const SOURCE_DIR = path.join(REPO_ROOT, "docs", "user-guide");
const OUT_DIR = path.join(REPO_ROOT, "apps", "web", "src", "docs", "content");

// breaks: true — a single newline (as used for the Audience/Purpose/Prerequisites lines at the
// top of every guide) becomes a visible line break, not silently joined into one run-on line.
marked.setOptions({ gfm: true, breaks: true });

function listSlugs(locale) {
  const dir = path.join(SOURCE_DIR, locale);
  return readdirSync(dir)
    .filter((f) => f.endsWith(".md"))
    .map((f) => f.replace(/\.md$/, ""))
    .sort();
}

function titleOf(markdown) {
  const match = /^#\s+(.+)$/m.exec(markdown);
  return match ? match[1].trim() : null;
}

/** Escapes a string for safe embedding inside a single-quoted TS template/string literal. */
function tsStringLiteral(value) {
  return "`" + value.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${") + "`";
}

function main() {
  const enSlugs = listSlugs("en");
  const jaSlugs = listSlugs("ja");
  const missingInJa = enSlugs.filter((s) => !jaSlugs.includes(s));
  const missingInEn = jaSlugs.filter((s) => !enSlugs.includes(s));
  if (missingInJa.length || missingInEn.length) {
    console.error("docs-render: English and Japanese guides are out of sync.");
    if (missingInJa.length) console.error(`  missing in ja/: ${missingInJa.join(", ")}`);
    if (missingInEn.length) console.error(`  missing in en/: ${missingInEn.join(", ")}`);
    process.exit(1);
  }

  mkdirSync(OUT_DIR, { recursive: true });
  const manifest = [];

  for (const slug of enSlugs) {
    for (const locale of ["en", "ja"]) {
      const srcPath = path.join(SOURCE_DIR, locale, `${slug}.md`);
      const markdown = readFileSync(srcPath, "utf8");
      const html = marked.parse(markdown);
      const title = titleOf(markdown) ?? slug;
      const outPath = path.join(OUT_DIR, `${slug}.${locale}.ts`);
      writeFileSync(
        outPath,
        `// Generated by apps/server/scripts/docs-render.mjs from docs/user-guide/${locale}/${slug}.md — do not edit directly.\n` +
          `export const title = ${JSON.stringify(title)};\n` +
          `export const html = ${tsStringLiteral(html)};\n`,
      );
      if (locale === "en") manifest.push({ slug, titleEn: title });
      else manifest[manifest.length - 1].titleJa = title;
    }
  }

  writeFileSync(
    path.join(OUT_DIR, "manifest.ts"),
    "// Generated by apps/server/scripts/docs-render.mjs — do not edit directly.\n" +
      "export interface DocManifestEntry { slug: string; titleEn: string; titleJa: string; }\n" +
      `export const DOCS_MANIFEST: DocManifestEntry[] = ${JSON.stringify(manifest, null, 2)};\n`,
  );

  console.log(`docs-render: wrote ${enSlugs.length} guide(s) x 2 locales to ${path.relative(REPO_ROOT, OUT_DIR)}/`);
}

main();
